### ISSUE TITLE
panic serving 127.0.0.1:15513: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by icemansven** [timabell/schema-explorer#24] opened 2020-04-29 08:45 UTC
I connect to a ERP Test Database, but it crashes after a few seconds.

2020/04/29 10:40:08 Connecting to mssql db
2020/04/29 10:40:08 Reading schema...
2020/04/29 10:40:08 Connecting to mssql db
2020/04/29 10:40:08 Checking database connection...
2020/04/29 10:40:08 Successfully connected to MSSQL. @@version: Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
2020/04/29 10:40:08 Reading schema, this may take a while...
2020/04/29 10:40:08 http: panic serving 127.0.0.1:15513: runtime error: invalid memory address or nil pointer dereference
goroutine 7972 [running]:
net/http.(*conn).serve.func1(0xc0005120a0)
        /home/tim/.gvm/gos/go1.11.1/src/net/http/server.go:1746 +0xd7
panic(0x9653e0, 0x8e12e0)
        /home/tim/.gvm/gos/go1.11.1/src/runtime/panic.go:513 +0x1c7
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/tim/.gvm/gos/go1.11.1/src/database/sql/sql.go:2953 +0x6d
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
        /home/tim/.gvm/gos/go1.11.1/src/database/sql/sql.go:2949 +0x3a
panic(0x9653e0, 0x8e12e0)
        /home/tim/.gvm/gos/go1.11.1/src/runtime/panic.go:513 +0x1c7
database/sql.(*Rows).Next(0x0, 0xe276a8)
        /home/tim/.gvm/gos/go1.11.1/src/database/sql/sql.go:2640 +0x37
bitbucket.org/timabell/sql-data-viewer/mssql.getColumns(0xc000591e00, 0xc000a4c840, 0xe276a8, 0x0, 0x0, 0xa67b20, 0xc000816440)
        /home/tim/repo/go/src/bitbucket.org/timabell/sql-data-viewer/mssql/mssql.go:575 +0x191
bitbucket.org/timabell/sql-data-viewer/mssql.mssqlModel.ReadSchema(0xc0000ae000, 0x0, 0x0, 0xc000b04e00, 0x0, 0x0)
        /home/tim/repo/go/src/bitbucket.org/timabell/sql-data-viewer/mssql/mssql.go:143 +0x202
bitbucket.org/timabell/sql-data-viewer/reader.InitializeDatabase(0x0, 0x0, 0x1, 0x0)
        /home/tim/repo/go/src/bitbucket.org/timabell/sql-data-viewer/reader/dbReader.go:52 +0x20b
bitbucket.org/timabell/sql-data-viewer/serve.dbRequestSetup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/tim/repo/go/src/bitbucket.org/timabell/sql-data-viewer/serve/host.go:93 +0x164
bitbucket.org/timabell/sql-data-viewer/serve.RootHandler(0xa6ad40, 0xc00099c9a0, 0xc000469a00)
        /home/tim/repo/go/src/bitbucket.org/timabell/sql-data-viewer/serve/table-handlers.go:86 +0x54
net/http.HandlerFunc.ServeHTTP(0xa04f88, 0xa6ad40, 0xc00099c9a0, 0xc000469a00)
        /home/tim/.gvm/gos/go1.11.1/src/net/http/server.go:1964 +0x4b
bitbucket.org/timabell/sql-data-viewer/serve.loggingHandler.func1(0xa6ad40, 0xc00099c9a0, 0xc000469a00)
        /home/tim/repo/go/src/bitbucket.org/timabell/sql-data-viewer/serve/logging.go:23 +0x1a9
net/http.HandlerFunc.ServeHTTP(0xc0003e7820, 0xa6ad40, 0xc00099c9a0, 0xc000469a00)
        /home/tim/.gvm/gos/go1.11.1/src/net/http/server.go:1964 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d21c0, 0xa6ad40, 0xc00099c9a0, 0xc000469a00)
        /home/tim/.gvm/pkgsets/go1.11.1/global/src/github.com/gorilla/mux/mux.go:162 +0xf8
net/http.serverHandler.ServeHTTP(0xc00007ca90, 0xa6ad40, 0xc00099c9a0, 0xc0003a8900)
        /home/tim/.gvm/gos/go1.11.1/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc0005120a0, 0xa6b040, 0xc00047b5c0)
        /home/tim/.gvm/gos/go1.11.1/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
        /home/tim/.gvm/gos/go1.11.1/src/net/http/server.go:2851 +0x2fc

**Comment by kmpm** [comment] 2020-04-29 11:27
Could you please try and see if you get the same with Go 1.13 or later?

**Comment by icemansven** [comment] 2020-04-29 12:29
I am running the Windows executable. How can I change to 1.13?

**Comment by timabell** [comment] 2020-05-01 16:51
> runtime error: invalid memory address or nil pointer dereference

that's bad, looks like `rows` is nil for some reason, and I see I missed an `err` check so we can't see what the actual error was.

nil error is here https://github.com/timabell/schema-explorer/blob/4ca93ef52a0f7dd8f3404cae6c185edc76529eeb/mssql/mssql.go#L575

the err return on https://github.com/timabell/schema-explorer/blob/4ca93ef52a0f7dd8f3404cae6c185edc76529eeb/mssql/mssql.go#L571 is incorrectly ignored

it needs the error handler adding and trying again to capture the error

**Comment by timabell** [comment] 2020-05-02 01:39
I've added the missing err/return, and made a temporary build which you can grab from https://www.dropbox.com/sh/jbsnfck6sl0bks2/AACqvhSNmfzwoVkKUtWMjIMua?dl=0
let me know what the output is!

**Comment by timabell** [comment] 2020-05-02 01:48
you can see me hacking away on it here https://youtu.be/_AAP3BR_ePI?t=1224 if you're reaaaaaly bored

**Comment by icemansven** [comment] 2020-05-02 12:05
Thanks for your time and video, but the windows bin is missing in the build. :-(

**Comment by timabell** [comment] 2020-05-02 14:21
Ah I probably didn't have the cross compiler installed.
Do you want try building from source yourself?

**Comment by timabell** [comment] 2020-05-02 20:18
Installed the missing dependencies and rebuilt.
Try again https://www.dropbox.com/sh/jbsnfck6sl0bks2/AACqvhSNmfzwoVkKUtWMjIMua?dl=0

**Comment by icemansven** [comment] 2020-05-03 11:36
The new build works now fine, but sadly the Database Designer used not the foreign key feature. Will there be view support in the future?

I wanted to use the software for helping me get insights for a small Microsoft Power BI Project.

For anyone who maybee read this. I would be cool to have a ML/AI App that uses the Profiler feature to build a graph for relations of tables and keys and get a rough data model.

And I tried a few days ago to run the source. But my knowledge with Open Source dev tool chain is greatly lacking. I use normally C# or VB.Net. And the Source Archiv was properly not up to date.

**Comment by timabell** [comment] 2020-05-12 09:58
Thanks for the update, I'll close this as the cause of the panic is resolved in `master`.

**Closed by timabell** 2020-05-12 09:58 UTC
Labels: bug

**Comment by timabell** [comment] 2020-05-12 10:00
For databases that lack foreign keys then #6 might be of interest
